version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: crud-nec
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
    volumes:
      - /c/desenvolvimento/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nec-network

  crud-backend:
    image: eliasneri/crud-backend-java17:latest
    restart: always
    ports:
      - "9598:9598"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - nec-network

  crud-nec:
    image: eliasneri/crud-nec:latest
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - crud-backend
    networks:
      - nec-network

networks:
  nec-network:
    driver: bridge
