version: '3.9'

services:
  nec-postgres:
    image: postgres:12-alpine
    restart: no
    environment:
      POSTGRES_DB: crud_nec
      POSTGRES_USER: nec
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    networks:
      - nec-network

  crud-backend:
    image: eliasneri/crud-backend-java17:latest
    restart: no
    ports:
      - "9598:9598"
    depends_on:
      - nec-postgres
    networks:
      - nec-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M  

networks:
  nec-network:
    driver: bridge